image: node:6.9.4

pipelines:
  pull-requests:
    '**':
      - step:
          name: Test
          caches:
            - node
          script:
            - npm install
            - npm run lint
            - npm run test
            - npm run build
